-- ============================================================================
-- RetailLens Master SQL Analytics Catalog (Phase 3)
-- Contains 20 Core Business Queries & Advanced Analytical SQL (CTEs, Window Functions)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CORE BUSINESS QUERIES (Milestone 2)
-- ----------------------------------------------------------------------------

-- Query 1: Total Net Revenue
-- Business Question: What is the total net monetary revenue generated across all completed sales?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_cancellation
SELECT 
    COALESCE(SUM(total_amount), 0.00) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE;


-- Query 2: Total Completed Orders
-- Business Question: How many distinct completed sales transactions occurred?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_invoice_no
SELECT 
    COUNT(DISTINCT invoice_no) AS total_orders
FROM fact_sales
WHERE is_cancellation = FALSE;


-- Query 3: Total Units Sold
-- Business Question: How many individual item units were sold across all orders?
-- Tables Used: fact_sales
SELECT 
    COALESCE(SUM(quantity), 0) AS total_units_sold
FROM fact_sales
WHERE is_cancellation = FALSE;


-- Query 4: Average Order Value (AOV)
-- Business Question: What is the average monetary value per completed order?
-- Formula: Total Net Revenue / Total Distinct Orders
-- Tables Used: fact_sales
SELECT 
    ROUND(
        COALESCE(SUM(total_amount), 0.00) / NULLIF(COUNT(DISTINCT invoice_no), 0), 2
    ) AS average_order_value
FROM fact_sales
WHERE is_cancellation = FALSE;


-- Query 5: Average Unit Price
-- Business Question: What is the average selling price per item?
-- Tables Used: fact_sales
SELECT 
    ROUND(AVG(unit_price), 2) AS average_unit_price
FROM fact_sales
WHERE is_cancellation = FALSE;


-- Query 6: Total Distinct Customers
-- Business Question: How many distinct buyers (including guest checkout marker) placed orders?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_customer_id
SELECT 
    COUNT(DISTINCT customer_id) AS total_customers
FROM fact_sales;


-- Query 7: Registered vs Guest Customer Count
-- Business Question: How many distinct registered customers vs guest checkouts exist?
-- Tables Used: fact_sales
SELECT 
    customer_type,
    COUNT(DISTINCT customer_id) AS customer_count
FROM fact_sales
GROUP BY customer_type;


-- Query 8: Revenue by Country
-- Business Question: How much revenue is generated by each geographic market?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_country
SELECT 
    country,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY country
ORDER BY total_revenue DESC;


-- Query 9: Revenue by Product
-- Business Question: What is the total sales performance of every product?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_stock_code
SELECT 
    stock_code,
    description,
    SUM(quantity) AS total_units_sold,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY stock_code, description
ORDER BY total_revenue DESC;


-- Query 10: Top 10 Products by Revenue
-- Business Question: Which 10 products generate the highest gross revenue?
-- Tables Used: fact_sales
SELECT 
    stock_code,
    description,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY stock_code, description
ORDER BY total_revenue DESC
LIMIT 10;


-- Query 11: Top 10 Products by Volume (Quantity Sold)
-- Business Question: Which 10 products have the highest unit sales volume?
-- Tables Used: fact_sales
SELECT 
    stock_code,
    description,
    SUM(quantity) AS total_units_sold
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY stock_code, description
ORDER BY total_units_sold DESC
LIMIT 10;


-- Query 12: Monthly Revenue Trend
-- Business Question: What is the total revenue and order volume broken down by month?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_year_month
SELECT 
    invoice_year,
    invoice_month,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY invoice_year, invoice_month
ORDER BY invoice_year ASC, invoice_month ASC;


-- Query 13: Quarterly Revenue Trend
-- Business Question: What is the quarterly revenue trajectory?
-- Tables Used: fact_sales
SELECT 
    invoice_year,
    invoice_quarter,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY invoice_year, invoice_quarter
ORDER BY invoice_year ASC, invoice_quarter ASC;


-- Query 14: Yearly Revenue Summary
-- Business Question: What is the annual gross revenue performance?
-- Tables Used: fact_sales
SELECT 
    invoice_year,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY invoice_year
ORDER BY invoice_year ASC;


-- Query 15: Daily Revenue Summary
-- Business Question: What is the daily revenue execution?
-- Tables Used: fact_sales
-- Index Tip: idx_fact_sales_timestamp
SELECT 
    DATE_TRUNC('day', invoice_timestamp) AS sales_date,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY DATE_TRUNC('day', invoice_timestamp)
ORDER BY sales_date ASC;


-- Query 16: Revenue Distribution by Day of Week
-- Business Question: Which weekdays generate the most sales activity?
-- Tables Used: fact_sales
SELECT 
    day_of_week,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY day_of_week
ORDER BY total_revenue DESC;


-- Query 17: Hourly Sales Activity
-- Business Question: What hours of the day experience peak order volume?
-- Tables Used: fact_sales
SELECT 
    invoice_hour,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY invoice_hour
ORDER BY invoice_hour ASC;


-- Query 18: Order Cancellation Rate
-- Business Question: What percentage of total generated invoices represent returns or cancellations?
-- Formula: (Cancelled Invoices / Total Invoices) * 100
-- Tables Used: fact_sales
SELECT 
    COUNT(DISTINCT invoice_no) AS total_invoices,
    COUNT(DISTINCT CASE WHEN is_cancellation = TRUE THEN invoice_no END) AS cancelled_invoices,
    ROUND(
        (COUNT(DISTINCT CASE WHEN is_cancellation = TRUE THEN invoice_no END)::NUMERIC / NULLIF(COUNT(DISTINCT invoice_no), 0)) * 100, 2
    ) AS cancellation_rate_pct
FROM fact_sales;


-- Query 19: Refund & Cancellation Monetary Loss
-- Business Question: How much total revenue was lost to cancellations and returns?
-- Tables Used: fact_sales
SELECT 
    ABS(SUM(total_amount)) AS total_cancellation_loss
FROM fact_sales
WHERE is_cancellation = TRUE;


-- Query 20: Revenue Breakdown by Customer Segment
-- Business Question: How much revenue comes from registered accounts vs guest checkouts?
-- Tables Used: fact_sales
SELECT 
    customer_type,
    COUNT(DISTINCT invoice_no) AS total_orders,
    SUM(total_amount) AS total_revenue,
    ROUND(AVG(total_amount), 2) AS avg_line_item_value
FROM fact_sales
WHERE is_cancellation = FALSE
GROUP BY customer_type;


-- ----------------------------------------------------------------------------
-- ADVANCED SQL ANALYTICS (Milestone 3: CTEs, Window Functions, Subqueries)
-- ----------------------------------------------------------------------------

-- Query 21: Month-over-Month (MoM) Revenue Growth Rate (CTE + LAG Window Function)
-- Business Question: What is the monthly revenue percentage growth rate compared to the previous month?
WITH monthly_revenue AS (
    SELECT 
        invoice_year,
        invoice_month,
        SUM(total_amount) AS current_month_revenue
    FROM fact_sales
    WHERE is_cancellation = FALSE
    GROUP BY invoice_year, invoice_month
),
monthly_with_lag AS (
    SELECT 
        invoice_year,
        invoice_month,
        current_month_revenue,
        LAG(current_month_revenue, 1) OVER (ORDER BY invoice_year, invoice_month) AS previous_month_revenue
    FROM monthly_revenue
)
SELECT 
    invoice_year,
    invoice_month,
    current_month_revenue,
    COALESCE(previous_month_revenue, 0.00) AS previous_month_revenue,
    ROUND(
        ((current_month_revenue - previous_month_revenue) / NULLIF(previous_month_revenue, 0.00)) * 100, 2
    ) AS mom_growth_pct
FROM monthly_with_lag
ORDER BY invoice_year ASC, invoice_month ASC;


-- Query 22: Top 3 Products per Country (CTE + DENSE_RANK Window Function)
-- Business Question: Which top 3 revenue-generating products belong to each country market?
WITH country_product_revenue AS (
    SELECT 
        country,
        stock_code,
        description,
        SUM(total_amount) AS total_revenue,
        DENSE_RANK() OVER (PARTITION BY country ORDER BY SUM(total_amount) DESC) AS revenue_rank
    FROM fact_sales
    WHERE is_cancellation = FALSE
    GROUP BY country, stock_code, description
)
SELECT 
    country,
    revenue_rank,
    stock_code,
    description,
    total_revenue
FROM country_product_revenue
WHERE revenue_rank <= 3
ORDER BY country ASC, revenue_rank ASC;


-- Query 23: Customer Spending Leaderboard with Percent Contribution (Window Functions)
-- Business Question: Rank customers by revenue and calculate their percentage contribution to total sales.
WITH customer_totals AS (
    SELECT 
        customer_id,
        customer_type,
        COUNT(DISTINCT invoice_no) AS total_orders,
        SUM(total_amount) AS total_spent
    FROM fact_sales
    WHERE is_cancellation = FALSE AND customer_id != 'GUEST'
    GROUP BY customer_id, customer_type
)
SELECT 
    DENSE_RANK() OVER (ORDER BY total_spent DESC) AS customer_rank,
    customer_id,
    customer_type,
    total_orders,
    total_spent,
    ROUND(
        (total_spent / SUM(total_spent) OVER ()) * 100, 2
    ) AS pct_of_total_revenue
FROM customer_totals
ORDER BY customer_rank ASC
LIMIT 20;


-- Query 24: Cumulative Running Total Revenue (Window Function)
-- Business Question: What is the cumulative running total revenue trajectory over time?
WITH daily_revenue AS (
    SELECT 
        DATE_TRUNC('day', invoice_timestamp) AS sales_date,
        SUM(total_amount) AS daily_revenue
    FROM fact_sales
    WHERE is_cancellation = FALSE
    GROUP BY DATE_TRUNC('day', invoice_timestamp)
)
SELECT 
    sales_date,
    daily_revenue,
    SUM(daily_revenue) OVER (ORDER BY sales_date ASC) AS cumulative_running_revenue
FROM daily_revenue
ORDER BY sales_date ASC;


-- Query 25: Customer Recency & Purchase Frequency Analysis (Subquery + Date Functions)
-- Business Question: Find the first purchase date, last purchase date, and order count for registered accounts.
SELECT 
    customer_id,
    COUNT(DISTINCT invoice_no) AS total_orders,
    MIN(invoice_timestamp) AS first_purchase_date,
    MAX(invoice_timestamp) AS last_purchase_date,
    SUM(total_amount) AS lifetime_value
FROM fact_sales
WHERE is_cancellation = FALSE AND customer_id != 'GUEST'
GROUP BY customer_id
HAVING COUNT(DISTINCT invoice_no) > 1
ORDER BY lifetime_value DESC;
